######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 11 12:18:45 2010
######################################################################

TEMPLATE = app
TARGET = notes_test
DEPENDPATH += .
INCLUDEPATH += . ../qt

# Input
HEADERS += ../qt/notes.h
SOURCES += ../qt/notes.cc notes_test.cc
